### ISSUE TITLE
Cannot run in docker

### ISSUE THREAD

**Issue by gamboz** [comments-ink/dci-project-stories#5]
I was trying to follow https://github.com/comments-ink/dci-project-stories?tab=readme-ov-file#2-run-in-docker but failed.

Because of some requirements issues I
-  changed docker image to python:3.10.14-slim-bookworm
-  set requirements to django-comments-ink==0.4.0

(please let me know I you would like a PR for this)

But, when I try to run the django container, I get "IsADirectoryError: [Errno 21] Is a directory: '..'" in `dotenv.read_dotenv("..")` in `manage.py`, which I don't understand :cry: 

I can run the project in my host OS (https://github.com/comments-ink/dci-project-stories#3-run-in-your-host-os), so the issue is probably only related to docker.

**Comment by danirus** [comment]
Hi @gamboz, thanks for reporting it.
Yes, the docker part needs to be updated. 
I will take a look sometime during the week and let you know. 
If you want to send a PR, it would be very nice.
